#+OPTIONS: \n:t
This installer builds by default emacspeak 49.0 with espeak or voxin
and works currently on Ubuntu 18.04.

Voxin (>=1.00) is optional and available at:
http://voxin.oralux.net

This installer may also help to build:
- another emacspeak archive,
- emacs, emacs-nox or emacspeak from the sources in development (git HEAD).
See paragraph 'Usage' for more details.

At the end of the build process, you will have to update your emacs or bash initfile.
The instructions are displayed on the console when the build is achieved and also copied at the end of the log file named log/install.xxx .

For example, for retrieving these instructions in a console, type:

# tail emacspeak_voxin_install-49.0-5/log/install.*

Then this kind of text should be displayed:

# Configuration
# Add this alias to ~/.bashrc:
alias emacs="/home/user1/emacspeak_voxin_install-49.0-5/build/install/bin/emacs"
# Add these lines to the top of your emacs init file (e.g. in  ~/.emacs )
(setenv "DTK_PROGRAM" "outloud")
(load-file "/lisp/emacspeak-setup.el")
# Now you may want to reboot, before launching emacs
# These instructions are copied at the end of log/install.*

* Build emacspeak 49.0
To download and build emacspeak 49.0, just type as a non-root user in
a terminal:
./install.sh

The proposed instruction to launch emacspeak will be displayed at the
end of the script.

* Emacs init file for emacspeak
In summary, update your emacs init file then start emacs.

For memo, the emacs init file is one of these three files:
~/.emacs
~/.emacs.el
~/.emacs.d/init.el


For example, if you have installed emacspeak_voxin_install in the
/home/user1 directory, the instruction to add at the beginning of your
emacs init file is:

(load-file "/home/user1/emacspeak_voxin_install/build/emacspeak-49.0/lisp/emacspeak-setup.el")

Then emacspeak will use espeak by default.

For using voxin, you may set the DTK_PROGRAM variable to
outloud before calling load-file:

(setenv "DTK_PROGRAM" "outloud")
(load-file "/home/user1/emacspeak_voxin_install/build/emacspeak-49.0/lisp/emacspeak-setup.el")

* alias to launch your locally build emacs
If you used this installer to build emacs from git, then you may want to add an emacs alias in your ~/.bashrc file to point to your local emacs binary. 
For example:
alias emacs="installDir/bin/emacs"

where install dir is the whole path pointing to the emacs directory.
This alias is indicated at the end of the log file (log/install.*)

* Usage

The following information are copied from:
./install.sh -h


This installer builds emacspeak with espeak or voxin.
By default, the emacspeak 49.0 archive is downloaded. 
But another emacspeak release or even its latest sources from GitHub
can be selected.

Optionally the developer version of emacs (git HEAD) can be
downloaded and built with or without X support.

OPTIONS
-c, --clean            clean all: delete the build, install directories and log file
-r, --release=version  download the indicated version (e.g. '49.0' or 'latest' for the developer version).
-e, --emacs            download and build emacs (by default with X support for graphical environment)
-f, --full             install the full dependencies (ladspa, youtube-dl, nodejs,...)
-n, --nox              build emacs without X support (for console based environment)
-h, --help             display this help 

EXAMPLES
# build emacspeak 49.0
 ./install.sh

# build emacspeak 49.0 and emacs (with X)
 ./install.sh --emacs

# build emacspeak 49.0 and emacs (without X)
 ./install.sh --nox

# build emacspeak 48.0
 ./install.sh --release 48.0

# build emacspeak from the currently developed sources (git HEAD)
 ./install.sh --release latest


